name: Build sdcard image for luckfox pico

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build-sdcard:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [rv1103, rv1106]
        include:
          - target: rv1103
            lunch_option: 1
          - target: rv1106
            lunch_option: 4

    container:
      image: debian:bookworm

    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y --no-install-recommends \
            sudo ca-certificates git xz-utils build-essential bash git ssh make gcc gcc-multilib g++-multilib module-assistant expect g++ gawk texinfo libssl-dev bison flex fakeroot cmake unzip gperf autoconf device-tree-compiler libncurses5-dev pkg-config bc python-is-python3 passwd openssl openssh-server openssh-client vim file cpio rsync wget curl genimage mtools dosfstools
          echo "ALL ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/github-actions

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Run build steps (${{ matrix.target }})
        shell: bash
        run: |
          set -e

          echo -e "${{ matrix.lunch_option }}\n0\n0" | ./build.sh lunch

          ./build.sh media
          ./build.sh
          ./finish-ohd.sh

      - name: Compress sdcard.img (${{ matrix.target }})
        run: |
          set -e
          cd output/genimage

          if [ ! -f sdcard.img ]; then
            echo "sdcard.img NOT FOUND!"
            ls -R .
            exit 1
          fi

          # Compress and rename per target (rv1103 / rv1106)
          xz -T0 -9 -f sdcard.img
          mv sdcard.img.xz sdcard-${{ matrix.target }}.img.xz

      - name: Upload image artifact (${{ matrix.target }})
        uses: actions/upload-artifact@v4
        with:
          name: sdcard-img-${{ matrix.target }}
          path: output/genimage/sdcard-${{ matrix.target }}.img.xz
          if-no-files-found: error